# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bind.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowBind(object):
    def setupUi(self, windowBind):
        windowBind.setObjectName("windowBind")
        windowBind.setWindowModality(QtCore.Qt.ApplicationModal)
        windowBind.resize(425, 165)
        self.keyBindingIndicator = QtWidgets.QLabel(windowBind)
        self.keyBindingIndicator.setGeometry(QtCore.QRect(108, 10, 175, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyBindingIndicator.sizePolicy().hasHeightForWidth())
        self.keyBindingIndicator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        self.keyBindingIndicator.setFont(font)
        self.keyBindingIndicator.setFocusPolicy(QtCore.Qt.TabFocus)
        self.keyBindingIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.keyBindingIndicator.setObjectName("keyBindingIndicator")
        self.bCancel = QtWidgets.QPushButton(windowBind)
        self.bCancel.setGeometry(QtCore.QRect(320, 135, 65, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCancel.sizePolicy().hasHeightForWidth())
        self.bCancel.setSizePolicy(sizePolicy)
        self.bCancel.setMinimumSize(QtCore.QSize(60, 26))
        self.bCancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bCancel.setObjectName("bCancel")
        self.bClear = QtWidgets.QPushButton(windowBind)
        self.bClear.setGeometry(QtCore.QRect(40, 135, 65, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bClear.sizePolicy().hasHeightForWidth())
        self.bClear.setSizePolicy(sizePolicy)
        self.bClear.setMinimumSize(QtCore.QSize(60, 26))
        self.bClear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bClear.setObjectName("bClear")
        self.bAccept = QtWidgets.QPushButton(windowBind)
        self.bAccept.setGeometry(QtCore.QRect(180, 135, 65, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAccept.sizePolicy().hasHeightForWidth())
        self.bAccept.setSizePolicy(sizePolicy)
        self.bAccept.setMinimumSize(QtCore.QSize(60, 26))
        self.bAccept.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bAccept.setObjectName("bAccept")
        self.buttonIndicator = QtWidgets.QLabel(windowBind)
        self.buttonIndicator.setGeometry(QtCore.QRect(10, 5, 64, 16))
        self.buttonIndicator.setObjectName("buttonIndicator")
        self.bF13 = QtWidgets.QPushButton(windowBind)
        self.bF13.setGeometry(QtCore.QRect(5, 75, 30, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bF13.sizePolicy().hasHeightForWidth())
        self.bF13.setSizePolicy(sizePolicy)
        self.bF13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF13.setObjectName("bF13")
        self.bF15 = QtWidgets.QPushButton(windowBind)
        self.bF15.setGeometry(QtCore.QRect(75, 75, 30, 28))
        self.bF15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF15.setObjectName("bF15")
        self.bF23 = QtWidgets.QPushButton(windowBind)
        self.bF23.setGeometry(QtCore.QRect(355, 75, 30, 28))
        self.bF23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF23.setObjectName("bF23")
        self.bF14 = QtWidgets.QPushButton(windowBind)
        self.bF14.setGeometry(QtCore.QRect(40, 75, 30, 28))
        self.bF14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF14.setObjectName("bF14")
        self.bF17 = QtWidgets.QPushButton(windowBind)
        self.bF17.setGeometry(QtCore.QRect(145, 75, 30, 28))
        self.bF17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF17.setObjectName("bF17")
        self.bF21 = QtWidgets.QPushButton(windowBind)
        self.bF21.setGeometry(QtCore.QRect(285, 75, 30, 28))
        self.bF21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF21.setObjectName("bF21")
        self.bF24 = QtWidgets.QPushButton(windowBind)
        self.bF24.setGeometry(QtCore.QRect(390, 75, 30, 28))
        self.bF24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF24.setObjectName("bF24")
        self.bF18 = QtWidgets.QPushButton(windowBind)
        self.bF18.setGeometry(QtCore.QRect(180, 75, 30, 28))
        self.bF18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF18.setObjectName("bF18")
        self.bF19 = QtWidgets.QPushButton(windowBind)
        self.bF19.setGeometry(QtCore.QRect(215, 75, 30, 28))
        self.bF19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF19.setObjectName("bF19")
        self.bF16 = QtWidgets.QPushButton(windowBind)
        self.bF16.setGeometry(QtCore.QRect(110, 75, 30, 28))
        self.bF16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF16.setObjectName("bF16")
        self.bF20 = QtWidgets.QPushButton(windowBind)
        self.bF20.setGeometry(QtCore.QRect(250, 75, 30, 28))
        self.bF20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF20.setObjectName("bF20")
        self.bF22 = QtWidgets.QPushButton(windowBind)
        self.bF22.setGeometry(QtCore.QRect(320, 75, 30, 28))
        self.bF22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bF22.setObjectName("bF22")
        self.bLCtrl = QtWidgets.QPushButton(windowBind)
        self.bLCtrl.setGeometry(QtCore.QRect(55, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLCtrl.sizePolicy().hasHeightForWidth())
        self.bLCtrl.setSizePolicy(sizePolicy)
        self.bLCtrl.setMinimumSize(QtCore.QSize(28, 28))
        self.bLCtrl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bLCtrl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bLCtrl.setObjectName("bLCtrl")
        self.bLShift = QtWidgets.QPushButton(windowBind)
        self.bLShift.setGeometry(QtCore.QRect(5, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLShift.sizePolicy().hasHeightForWidth())
        self.bLShift.setSizePolicy(sizePolicy)
        self.bLShift.setMinimumSize(QtCore.QSize(28, 28))
        self.bLShift.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bLShift.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bLShift.setObjectName("bLShift")
        self.bLAlt = QtWidgets.QPushButton(windowBind)
        self.bLAlt.setGeometry(QtCore.QRect(155, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLAlt.sizePolicy().hasHeightForWidth())
        self.bLAlt.setSizePolicy(sizePolicy)
        self.bLAlt.setMinimumSize(QtCore.QSize(28, 28))
        self.bLAlt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bLAlt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bLAlt.setObjectName("bLAlt")
        self.bLSuper = QtWidgets.QPushButton(windowBind)
        self.bLSuper.setGeometry(QtCore.QRect(105, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLSuper.sizePolicy().hasHeightForWidth())
        self.bLSuper.setSizePolicy(sizePolicy)
        self.bLSuper.setMinimumSize(QtCore.QSize(28, 28))
        self.bLSuper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bLSuper.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bLSuper.setObjectName("bLSuper")
        self.bRShift = QtWidgets.QPushButton(windowBind)
        self.bRShift.setGeometry(QtCore.QRect(375, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRShift.sizePolicy().hasHeightForWidth())
        self.bRShift.setSizePolicy(sizePolicy)
        self.bRShift.setMinimumSize(QtCore.QSize(28, 28))
        self.bRShift.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bRShift.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bRShift.setObjectName("bRShift")
        self.bRCtrl = QtWidgets.QPushButton(windowBind)
        self.bRCtrl.setGeometry(QtCore.QRect(325, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRCtrl.sizePolicy().hasHeightForWidth())
        self.bRCtrl.setSizePolicy(sizePolicy)
        self.bRCtrl.setMinimumSize(QtCore.QSize(28, 28))
        self.bRCtrl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bRCtrl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bRCtrl.setObjectName("bRCtrl")
        self.bRAlt = QtWidgets.QPushButton(windowBind)
        self.bRAlt.setGeometry(QtCore.QRect(225, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRAlt.sizePolicy().hasHeightForWidth())
        self.bRAlt.setSizePolicy(sizePolicy)
        self.bRAlt.setMinimumSize(QtCore.QSize(28, 28))
        self.bRAlt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bRAlt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bRAlt.setObjectName("bRAlt")
        self.bRSuper = QtWidgets.QPushButton(windowBind)
        self.bRSuper.setGeometry(QtCore.QRect(275, 105, 45, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRSuper.sizePolicy().hasHeightForWidth())
        self.bRSuper.setSizePolicy(sizePolicy)
        self.bRSuper.setMinimumSize(QtCore.QSize(28, 28))
        self.bRSuper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bRSuper.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bRSuper.setObjectName("bRSuper")
        self.bModeKEYB = QtWidgets.QPushButton(windowBind)
        self.bModeKEYB.setGeometry(QtCore.QRect(360, 10, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bModeKEYB.sizePolicy().hasHeightForWidth())
        self.bModeKEYB.setSizePolicy(sizePolicy)
        self.bModeKEYB.setMinimumSize(QtCore.QSize(28, 20))
        self.bModeKEYB.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bModeKEYB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bModeKEYB.setObjectName("bModeKEYB")
        self.bModeGPAD = QtWidgets.QPushButton(windowBind)
        self.bModeGPAD.setGeometry(QtCore.QRect(360, 30, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bModeGPAD.sizePolicy().hasHeightForWidth())
        self.bModeGPAD.setSizePolicy(sizePolicy)
        self.bModeGPAD.setMinimumSize(QtCore.QSize(28, 20))
        self.bModeGPAD.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bModeGPAD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bModeGPAD.setObjectName("bModeGPAD")
        self.bModeBOTH = QtWidgets.QPushButton(windowBind)
        self.bModeBOTH.setGeometry(QtCore.QRect(360, 50, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bModeBOTH.sizePolicy().hasHeightForWidth())
        self.bModeBOTH.setSizePolicy(sizePolicy)
        self.bModeBOTH.setMinimumSize(QtCore.QSize(28, 20))
        self.bModeBOTH.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bModeBOTH.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bModeBOTH.setObjectName("bModeBOTH")
        self.keyBindingIndicator.raise_()
        self.bCancel.raise_()
        self.bAccept.raise_()
        self.buttonIndicator.raise_()
        self.bClear.raise_()
        self.bF13.raise_()
        self.bF15.raise_()
        self.bF23.raise_()
        self.bF14.raise_()
        self.bF17.raise_()
        self.bF21.raise_()
        self.bF24.raise_()
        self.bF18.raise_()
        self.bF19.raise_()
        self.bF16.raise_()
        self.bF20.raise_()
        self.bF22.raise_()
        self.bLCtrl.raise_()
        self.bLShift.raise_()
        self.bLAlt.raise_()
        self.bLSuper.raise_()
        self.bRShift.raise_()
        self.bRCtrl.raise_()
        self.bRAlt.raise_()
        self.bRSuper.raise_()
        self.bModeKEYB.raise_()
        self.bModeGPAD.raise_()
        self.bModeBOTH.raise_()

        self.retranslateUi(windowBind)
        QtCore.QMetaObject.connectSlotsByName(windowBind)
        windowBind.setTabOrder(self.bClear, self.bAccept)
        windowBind.setTabOrder(self.bAccept, self.bCancel)

    def retranslateUi(self, windowBind):
        _translate = QtCore.QCoreApplication.translate
        windowBind.setWindowTitle(_translate("windowBind", "Binding..."))
        self.keyBindingIndicator.setText(_translate("windowBind", "F1"))
        self.bCancel.setText(_translate("windowBind", "Cancel"))
        self.bClear.setText(_translate("windowBind", "Clear"))
        self.bAccept.setText(_translate("windowBind", "Accept"))
        self.buttonIndicator.setText(_translate("windowBind", "fingerB#"))
        self.bF13.setText(_translate("windowBind", "F13"))
        self.bF15.setText(_translate("windowBind", "F15"))
        self.bF23.setText(_translate("windowBind", "F23"))
        self.bF14.setText(_translate("windowBind", "F14"))
        self.bF17.setText(_translate("windowBind", "F17"))
        self.bF21.setText(_translate("windowBind", "F21"))
        self.bF24.setText(_translate("windowBind", "F24"))
        self.bF18.setText(_translate("windowBind", "F18"))
        self.bF19.setText(_translate("windowBind", "F19"))
        self.bF16.setText(_translate("windowBind", "F16"))
        self.bF20.setText(_translate("windowBind", "F20"))
        self.bF22.setText(_translate("windowBind", "F22"))
        self.bLCtrl.setText(_translate("windowBind", "LCtrl"))
        self.bLShift.setText(_translate("windowBind", "LShift"))
        self.bLAlt.setText(_translate("windowBind", "LAlt"))
        self.bLSuper.setText(_translate("windowBind", "LSuper"))
        self.bRShift.setText(_translate("windowBind", "RShift"))
        self.bRCtrl.setText(_translate("windowBind", "RCtrl"))
        self.bRAlt.setText(_translate("windowBind", "RAlt"))
        self.bRSuper.setText(_translate("windowBind", "RSuper"))
        self.bModeKEYB.setText(_translate("windowBind", "KEYB"))
        self.bModeGPAD.setText(_translate("windowBind", "GPAD"))
        self.bModeBOTH.setText(_translate("windowBind", "BOTH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowBind = QtWidgets.QWidget()
    ui = Ui_windowBind()
    ui.setupUi(windowBind)
    windowBind.show()
    sys.exit(app.exec_())
