# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowMain(object):
    def setupUi(self, windowMain):
        windowMain.setObjectName("windowMain")
        windowMain.resize(935, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(windowMain.sizePolicy().hasHeightForWidth())
        windowMain.setSizePolicy(sizePolicy)
        windowMain.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(windowMain)
        self.centralwidget.setObjectName("centralwidget")
        self.comList = QtWidgets.QComboBox(self.centralwidget)
        self.comList.setGeometry(QtCore.QRect(5, 5, 150, 28))
        self.comList.setObjectName("comList")
        self.grpMiddle = QtWidgets.QGroupBox(self.centralwidget)
        self.grpMiddle.setGeometry(QtCore.QRect(375, 295, 185, 185))
        self.grpMiddle.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMiddle.setFlat(False)
        self.grpMiddle.setObjectName("grpMiddle")
        self.lMiddleB3 = QtWidgets.QLabel(self.grpMiddle)
        self.lMiddleB3.setGeometry(QtCore.QRect(85, 150, 20, 25))
        self.lMiddleB3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lMiddleB3.setObjectName("lMiddleB3")
        self.kMiddleB3 = QtWidgets.QPushButton(self.grpMiddle)
        self.kMiddleB3.setGeometry(QtCore.QRect(110, 150, 35, 25))
        self.kMiddleB3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kMiddleB3.setText("")
        self.kMiddleB3.setObjectName("kMiddleB3")
        self.lMiddleB2 = QtWidgets.QLabel(self.grpMiddle)
        self.lMiddleB2.setGeometry(QtCore.QRect(25, 135, 20, 25))
        self.lMiddleB2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lMiddleB2.setObjectName("lMiddleB2")
        self.lMiddleB4 = QtWidgets.QLabel(self.grpMiddle)
        self.lMiddleB4.setGeometry(QtCore.QRect(115, 100, 20, 25))
        self.lMiddleB4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lMiddleB4.setObjectName("lMiddleB4")
        self.kMiddleB4 = QtWidgets.QPushButton(self.grpMiddle)
        self.kMiddleB4.setGeometry(QtCore.QRect(140, 100, 35, 25))
        self.kMiddleB4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kMiddleB4.setText("")
        self.kMiddleB4.setObjectName("kMiddleB4")
        self.kMiddleB2 = QtWidgets.QPushButton(self.grpMiddle)
        self.kMiddleB2.setGeometry(QtCore.QRect(50, 135, 35, 25))
        self.kMiddleB2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kMiddleB2.setText("")
        self.kMiddleB2.setObjectName("kMiddleB2")
        self.kMiddleB5 = QtWidgets.QPushButton(self.grpMiddle)
        self.kMiddleB5.setGeometry(QtCore.QRect(115, 45, 35, 25))
        self.kMiddleB5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kMiddleB5.setText("")
        self.kMiddleB5.setObjectName("kMiddleB5")
        self.kMiddleB1 = QtWidgets.QPushButton(self.grpMiddle)
        self.kMiddleB1.setGeometry(QtCore.QRect(30, 100, 35, 25))
        self.kMiddleB1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kMiddleB1.setText("")
        self.kMiddleB1.setObjectName("kMiddleB1")
        self.lMiddleB1 = QtWidgets.QLabel(self.grpMiddle)
        self.lMiddleB1.setGeometry(QtCore.QRect(5, 100, 20, 25))
        self.lMiddleB1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lMiddleB1.setObjectName("lMiddleB1")
        self.lMiddleB5 = QtWidgets.QLabel(self.grpMiddle)
        self.lMiddleB5.setGeometry(QtCore.QRect(90, 45, 20, 25))
        self.lMiddleB5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lMiddleB5.setObjectName("lMiddleB5")
        self.grpPinky = QtWidgets.QGroupBox(self.centralwidget)
        self.grpPinky.setGeometry(QtCore.QRect(5, 295, 185, 185))
        self.grpPinky.setAlignment(QtCore.Qt.AlignCenter)
        self.grpPinky.setFlat(False)
        self.grpPinky.setObjectName("grpPinky")
        self.lPinkyB1 = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyB1.setGeometry(QtCore.QRect(5, 100, 20, 25))
        self.lPinkyB1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyB1.setObjectName("lPinkyB1")
        self.lPinkyB2 = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyB2.setGeometry(QtCore.QRect(25, 135, 20, 25))
        self.lPinkyB2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyB2.setObjectName("lPinkyB2")
        self.lPinkyB3 = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyB3.setGeometry(QtCore.QRect(85, 150, 20, 25))
        self.lPinkyB3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyB3.setObjectName("lPinkyB3")
        self.lPinkyB4 = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyB4.setGeometry(QtCore.QRect(115, 100, 20, 25))
        self.lPinkyB4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyB4.setObjectName("lPinkyB4")
        self.lPinkyB5 = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyB5.setGeometry(QtCore.QRect(90, 45, 20, 25))
        self.lPinkyB5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyB5.setObjectName("lPinkyB5")
        self.lPinkyBAddon = QtWidgets.QLabel(self.grpPinky)
        self.lPinkyBAddon.setGeometry(QtCore.QRect(5, 25, 31, 25))
        self.lPinkyBAddon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lPinkyBAddon.setObjectName("lPinkyBAddon")
        self.kPinkyB1 = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyB1.setGeometry(QtCore.QRect(30, 100, 35, 25))
        self.kPinkyB1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyB1.setText("")
        self.kPinkyB1.setObjectName("kPinkyB1")
        self.kPinkyB2 = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyB2.setGeometry(QtCore.QRect(50, 135, 35, 25))
        self.kPinkyB2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyB2.setText("")
        self.kPinkyB2.setObjectName("kPinkyB2")
        self.kPinkyB3 = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyB3.setGeometry(QtCore.QRect(110, 150, 35, 25))
        self.kPinkyB3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyB3.setText("")
        self.kPinkyB3.setObjectName("kPinkyB3")
        self.kPinkyB4 = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyB4.setGeometry(QtCore.QRect(140, 100, 35, 25))
        self.kPinkyB4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyB4.setText("")
        self.kPinkyB4.setObjectName("kPinkyB4")
        self.kPinkyB5 = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyB5.setGeometry(QtCore.QRect(115, 45, 35, 25))
        self.kPinkyB5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyB5.setText("")
        self.kPinkyB5.setObjectName("kPinkyB5")
        self.kPinkyBAddon = QtWidgets.QPushButton(self.grpPinky)
        self.kPinkyBAddon.setGeometry(QtCore.QRect(40, 25, 35, 25))
        self.kPinkyBAddon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kPinkyBAddon.setText("")
        self.kPinkyBAddon.setObjectName("kPinkyBAddon")
        self.chkPinkyAddon = QtWidgets.QCheckBox(self.grpPinky)
        self.chkPinkyAddon.setEnabled(False)
        self.chkPinkyAddon.setGeometry(QtCore.QRect(5, 165, 82, 15))
        self.chkPinkyAddon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkPinkyAddon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPinkyAddon.setChecked(True)
        self.chkPinkyAddon.setObjectName("chkPinkyAddon")
        self.grpRing = QtWidgets.QGroupBox(self.centralwidget)
        self.grpRing.setGeometry(QtCore.QRect(190, 295, 185, 185))
        self.grpRing.setAcceptDrops(False)
        self.grpRing.setAlignment(QtCore.Qt.AlignCenter)
        self.grpRing.setFlat(False)
        self.grpRing.setObjectName("grpRing")
        self.lRingB3 = QtWidgets.QLabel(self.grpRing)
        self.lRingB3.setGeometry(QtCore.QRect(85, 150, 20, 25))
        self.lRingB3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRingB3.setObjectName("lRingB3")
        self.kRingB3 = QtWidgets.QPushButton(self.grpRing)
        self.kRingB3.setGeometry(QtCore.QRect(110, 150, 35, 25))
        self.kRingB3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kRingB3.setText("")
        self.kRingB3.setObjectName("kRingB3")
        self.lRingB2 = QtWidgets.QLabel(self.grpRing)
        self.lRingB2.setGeometry(QtCore.QRect(25, 135, 20, 25))
        self.lRingB2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRingB2.setObjectName("lRingB2")
        self.lRingB4 = QtWidgets.QLabel(self.grpRing)
        self.lRingB4.setGeometry(QtCore.QRect(115, 100, 20, 25))
        self.lRingB4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRingB4.setObjectName("lRingB4")
        self.kRingB4 = QtWidgets.QPushButton(self.grpRing)
        self.kRingB4.setGeometry(QtCore.QRect(140, 100, 35, 25))
        self.kRingB4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kRingB4.setText("")
        self.kRingB4.setObjectName("kRingB4")
        self.kRingB2 = QtWidgets.QPushButton(self.grpRing)
        self.kRingB2.setGeometry(QtCore.QRect(50, 135, 35, 25))
        self.kRingB2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kRingB2.setText("")
        self.kRingB2.setObjectName("kRingB2")
        self.kRingB5 = QtWidgets.QPushButton(self.grpRing)
        self.kRingB5.setGeometry(QtCore.QRect(115, 45, 35, 25))
        self.kRingB5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kRingB5.setText("")
        self.kRingB5.setObjectName("kRingB5")
        self.kRingB1 = QtWidgets.QPushButton(self.grpRing)
        self.kRingB1.setGeometry(QtCore.QRect(30, 100, 35, 25))
        self.kRingB1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kRingB1.setText("")
        self.kRingB1.setObjectName("kRingB1")
        self.lRingB1 = QtWidgets.QLabel(self.grpRing)
        self.lRingB1.setGeometry(QtCore.QRect(5, 100, 20, 25))
        self.lRingB1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRingB1.setObjectName("lRingB1")
        self.lRingB5 = QtWidgets.QLabel(self.grpRing)
        self.lRingB5.setGeometry(QtCore.QRect(90, 45, 20, 25))
        self.lRingB5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRingB5.setObjectName("lRingB5")
        self.bSendAll = QtWidgets.QPushButton(self.centralwidget)
        self.bSendAll.setGeometry(QtCore.QRect(470, 5, 150, 28))
        self.bSendAll.setObjectName("bSendAll")
        self.grpIndex = QtWidgets.QGroupBox(self.centralwidget)
        self.grpIndex.setGeometry(QtCore.QRect(560, 295, 185, 185))
        self.grpIndex.setAlignment(QtCore.Qt.AlignCenter)
        self.grpIndex.setFlat(False)
        self.grpIndex.setObjectName("grpIndex")
        self.chkIndexAddon = QtWidgets.QCheckBox(self.grpIndex)
        self.chkIndexAddon.setEnabled(False)
        self.chkIndexAddon.setGeometry(QtCore.QRect(5, 165, 82, 15))
        self.chkIndexAddon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkIndexAddon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkIndexAddon.setChecked(True)
        self.chkIndexAddon.setObjectName("chkIndexAddon")
        self.lIndexBAddon = QtWidgets.QLabel(self.grpIndex)
        self.lIndexBAddon.setGeometry(QtCore.QRect(5, 25, 31, 25))
        self.lIndexBAddon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexBAddon.setObjectName("lIndexBAddon")
        self.lIndexB3 = QtWidgets.QLabel(self.grpIndex)
        self.lIndexB3.setGeometry(QtCore.QRect(85, 150, 20, 25))
        self.lIndexB3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexB3.setObjectName("lIndexB3")
        self.kIndexBAddon = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexBAddon.setGeometry(QtCore.QRect(40, 25, 35, 25))
        self.kIndexBAddon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexBAddon.setText("")
        self.kIndexBAddon.setObjectName("kIndexBAddon")
        self.kIndexB3 = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexB3.setGeometry(QtCore.QRect(110, 150, 35, 25))
        self.kIndexB3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexB3.setText("")
        self.kIndexB3.setObjectName("kIndexB3")
        self.lIndexB2 = QtWidgets.QLabel(self.grpIndex)
        self.lIndexB2.setGeometry(QtCore.QRect(25, 135, 20, 25))
        self.lIndexB2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexB2.setObjectName("lIndexB2")
        self.lIndexB4 = QtWidgets.QLabel(self.grpIndex)
        self.lIndexB4.setGeometry(QtCore.QRect(115, 100, 20, 25))
        self.lIndexB4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexB4.setObjectName("lIndexB4")
        self.kIndexB4 = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexB4.setGeometry(QtCore.QRect(140, 100, 35, 25))
        self.kIndexB4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexB4.setText("")
        self.kIndexB4.setObjectName("kIndexB4")
        self.kIndexB2 = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexB2.setGeometry(QtCore.QRect(50, 135, 35, 25))
        self.kIndexB2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexB2.setText("")
        self.kIndexB2.setObjectName("kIndexB2")
        self.kIndexB5 = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexB5.setGeometry(QtCore.QRect(115, 45, 35, 25))
        self.kIndexB5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexB5.setText("")
        self.kIndexB5.setObjectName("kIndexB5")
        self.kIndexB1 = QtWidgets.QPushButton(self.grpIndex)
        self.kIndexB1.setGeometry(QtCore.QRect(30, 100, 35, 25))
        self.kIndexB1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kIndexB1.setText("")
        self.kIndexB1.setObjectName("kIndexB1")
        self.lIndexB1 = QtWidgets.QLabel(self.grpIndex)
        self.lIndexB1.setGeometry(QtCore.QRect(5, 100, 20, 25))
        self.lIndexB1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexB1.setObjectName("lIndexB1")
        self.lIndexB5 = QtWidgets.QLabel(self.grpIndex)
        self.lIndexB5.setGeometry(QtCore.QRect(90, 45, 20, 25))
        self.lIndexB5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lIndexB5.setObjectName("lIndexB5")
        self.bClearAll = QtWidgets.QPushButton(self.centralwidget)
        self.bClearAll.setGeometry(QtCore.QRect(625, 5, 150, 28))
        self.bClearAll.setObjectName("bClearAll")
        self.grpThumbNav = QtWidgets.QGroupBox(self.centralwidget)
        self.grpThumbNav.setGeometry(QtCore.QRect(745, 295, 185, 185))
        self.grpThumbNav.setAlignment(QtCore.Qt.AlignCenter)
        self.grpThumbNav.setFlat(False)
        self.grpThumbNav.setObjectName("grpThumbNav")
        self.lThumbNavN = QtWidgets.QLabel(self.grpThumbNav)
        self.lThumbNavN.setGeometry(QtCore.QRect(65, 20, 55, 25))
        self.lThumbNavN.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbNavN.setObjectName("lThumbNavN")
        self.lThumbNavS = QtWidgets.QLabel(self.grpThumbNav)
        self.lThumbNavS.setGeometry(QtCore.QRect(65, 155, 55, 25))
        self.lThumbNavS.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbNavS.setObjectName("lThumbNavS")
        self.lThumbNavE = QtWidgets.QLabel(self.grpThumbNav)
        self.lThumbNavE.setGeometry(QtCore.QRect(115, 105, 55, 25))
        self.lThumbNavE.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbNavE.setObjectName("lThumbNavE")
        self.lThumbNavW = QtWidgets.QLabel(self.grpThumbNav)
        self.lThumbNavW.setGeometry(QtCore.QRect(15, 105, 55, 25))
        self.lThumbNavW.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbNavW.setObjectName("lThumbNavW")
        self.lThumbNavPush = QtWidgets.QLabel(self.grpThumbNav)
        self.lThumbNavPush.setGeometry(QtCore.QRect(65, 105, 55, 25))
        self.lThumbNavPush.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbNavPush.setObjectName("lThumbNavPush")
        self.kThumbNavS = QtWidgets.QPushButton(self.grpThumbNav)
        self.kThumbNavS.setGeometry(QtCore.QRect(75, 130, 35, 25))
        self.kThumbNavS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbNavS.setText("")
        self.kThumbNavS.setObjectName("kThumbNavS")
        self.kThumbNavPush = QtWidgets.QPushButton(self.grpThumbNav)
        self.kThumbNavPush.setGeometry(QtCore.QRect(75, 80, 35, 25))
        self.kThumbNavPush.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbNavPush.setText("")
        self.kThumbNavPush.setObjectName("kThumbNavPush")
        self.kThumbNavW = QtWidgets.QPushButton(self.grpThumbNav)
        self.kThumbNavW.setGeometry(QtCore.QRect(25, 80, 35, 25))
        self.kThumbNavW.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbNavW.setText("")
        self.kThumbNavW.setObjectName("kThumbNavW")
        self.kThumbNavE = QtWidgets.QPushButton(self.grpThumbNav)
        self.kThumbNavE.setGeometry(QtCore.QRect(125, 80, 35, 25))
        self.kThumbNavE.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbNavE.setText("")
        self.kThumbNavE.setObjectName("kThumbNavE")
        self.kThumbNavN = QtWidgets.QPushButton(self.grpThumbNav)
        self.kThumbNavN.setGeometry(QtCore.QRect(75, 45, 35, 25))
        self.kThumbNavN.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbNavN.setText("")
        self.kThumbNavN.setObjectName("kThumbNavN")
        self.bScanSerial = QtWidgets.QPushButton(self.centralwidget)
        self.bScanSerial.setGeometry(QtCore.QRect(160, 5, 150, 28))
        self.bScanSerial.setObjectName("bScanSerial")
        self.bRetrieve = QtWidgets.QPushButton(self.centralwidget)
        self.bRetrieve.setGeometry(QtCore.QRect(315, 5, 150, 28))
        self.bRetrieve.setObjectName("bRetrieve")
        self.grpConfig = QtWidgets.QGroupBox(self.centralwidget)
        self.grpConfig.setGeometry(QtCore.QRect(5, 35, 155, 221))
        self.grpConfig.setObjectName("grpConfig")
        self.configChooser = QtWidgets.QComboBox(self.grpConfig)
        self.configChooser.setGeometry(QtCore.QRect(5, 25, 145, 20))
        self.configChooser.setObjectName("configChooser")
        self.bConfigSave = QtWidgets.QPushButton(self.grpConfig)
        self.bConfigSave.setGeometry(QtCore.QRect(5, 50, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bConfigSave.setFont(font)
        self.bConfigSave.setObjectName("bConfigSave")
        self.bConfigSaveAs = QtWidgets.QPushButton(self.grpConfig)
        self.bConfigSaveAs.setGeometry(QtCore.QRect(80, 50, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bConfigSaveAs.setFont(font)
        self.bConfigSaveAs.setObjectName("bConfigSaveAs")
        self.bConfigRefresh = QtWidgets.QPushButton(self.grpConfig)
        self.bConfigRefresh.setGeometry(QtCore.QRect(5, 75, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.bConfigRefresh.setFont(font)
        self.bConfigRefresh.setObjectName("bConfigRefresh")
        self.bConfigLoad = QtWidgets.QPushButton(self.grpConfig)
        self.bConfigLoad.setGeometry(QtCore.QRect(80, 75, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bConfigLoad.setFont(font)
        self.bConfigLoad.setObjectName("bConfigLoad")
        self.fDevInfo = QtWidgets.QFrame(self.grpConfig)
        self.fDevInfo.setGeometry(QtCore.QRect(5, 185, 145, 30))
        self.fDevInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fDevInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fDevInfo.setObjectName("fDevInfo")
        self.lDevFirmware = QtWidgets.QLabel(self.fDevInfo)
        self.lDevFirmware.setGeometry(QtCore.QRect(75, 15, 100, 14))
        self.lDevFirmware.setText("")
        self.lDevFirmware.setObjectName("lDevFirmware")
        self.lDevN = QtWidgets.QLabel(self.fDevInfo)
        self.lDevN.setGeometry(QtCore.QRect(5, 0, 65, 14))
        self.lDevN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lDevN.setObjectName("lDevN")
        self.lDevF = QtWidgets.QLabel(self.fDevInfo)
        self.lDevF.setGeometry(QtCore.QRect(5, 15, 65, 14))
        self.lDevF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lDevF.setObjectName("lDevF")
        self.lDevName = QtWidgets.QLabel(self.fDevInfo)
        self.lDevName.setGeometry(QtCore.QRect(75, 0, 100, 14))
        self.lDevName.setText("")
        self.lDevName.setObjectName("lDevName")
        self.bSaveEEPROM = QtWidgets.QPushButton(self.centralwidget)
        self.bSaveEEPROM.setGeometry(QtCore.QRect(780, 5, 150, 28))
        self.bSaveEEPROM.setObjectName("bSaveEEPROM")
        self.grpStick = QtWidgets.QGroupBox(self.centralwidget)
        self.grpStick.setGeometry(QtCore.QRect(160, 35, 770, 260))
        self.grpStick.setObjectName("grpStick")
        self.sliderXrange = QLabeledRangeSlider(self.grpStick)
        self.sliderXrange.setGeometry(QtCore.QRect(65, 210, 700, 45))
        self.sliderXrange.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sliderXrange.setMaximum(1023)
        self.sliderXrange.setSingleStep(1)
        self.sliderXrange.setPageStep(50)
        self.sliderXrange.setSliderPosition(511)
        self.sliderXrange.setOrientation(QtCore.Qt.Horizontal)
        self.sliderXrange.setObjectName("sliderXrange")
        self.lXCur = QtWidgets.QLabel(self.grpStick)
        self.lXCur.setGeometry(QtCore.QRect(40, 65, 60, 20))
        self.lXCur.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lXCur.setAlignment(QtCore.Qt.AlignCenter)
        self.lXCur.setObjectName("lXCur")
        self.lYCur = QtWidgets.QLabel(self.grpStick)
        self.lYCur.setGeometry(QtCore.QRect(670, 65, 60, 20))
        self.lYCur.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lYCur.setAlignment(QtCore.Qt.AlignCenter)
        self.lYCur.setObjectName("lYCur")
        self.iXInvert = QtWidgets.QCheckBox(self.grpStick)
        self.iXInvert.setGeometry(QtCore.QRect(35, 165, 75, 21))
        self.iXInvert.setObjectName("iXInvert")
        self.iYInvert = QtWidgets.QCheckBox(self.grpStick)
        self.iYInvert.setGeometry(QtCore.QRect(665, 165, 75, 21))
        self.iYInvert.setObjectName("iYInvert")
        self.oYCur = QtWidgets.QLabel(self.grpStick)
        self.oYCur.setGeometry(QtCore.QRect(675, 85, 50, 20))
        self.oYCur.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oYCur.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.oYCur.setText("")
        self.oYCur.setAlignment(QtCore.Qt.AlignCenter)
        self.oYCur.setObjectName("oYCur")
        self.oXCur = QtWidgets.QLabel(self.grpStick)
        self.oXCur.setGeometry(QtCore.QRect(45, 85, 50, 20))
        self.oXCur.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oXCur.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.oXCur.setText("")
        self.oXCur.setAlignment(QtCore.Qt.AlignCenter)
        self.oXCur.setObjectName("oXCur")
        self.bResetAxes = QtWidgets.QPushButton(self.grpStick)
        self.bResetAxes.setGeometry(QtCore.QRect(190, 115, 105, 20))
        self.bResetAxes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bResetAxes.setObjectName("bResetAxes")
        self.bSendAxes = QtWidgets.QPushButton(self.grpStick)
        self.bSendAxes.setGeometry(QtCore.QRect(190, 90, 105, 20))
        self.bSendAxes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bSendAxes.setObjectName("bSendAxes")
        self.bUpdateAnalog = QtWidgets.QPushButton(self.grpStick)
        self.bUpdateAnalog.setGeometry(QtCore.QRect(190, 140, 105, 20))
        self.bUpdateAnalog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bUpdateAnalog.setObjectName("bUpdateAnalog")
        self.sliderYrange = QLabeledRangeSlider(self.grpStick)
        self.sliderYrange.setGeometry(QtCore.QRect(65, 25, 700, 45))
        self.sliderYrange.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sliderYrange.setMaximum(1023)
        self.sliderYrange.setSingleStep(1)
        self.sliderYrange.setPageStep(50)
        self.sliderYrange.setSliderPosition(511)
        self.sliderYrange.setOrientation(QtCore.Qt.Horizontal)
        self.sliderYrange.setObjectName("sliderYrange")
        self.dialYdz = QtWidgets.QDial(self.grpStick)
        self.dialYdz.setGeometry(QtCore.QRect(700, 110, 50, 50))
        self.dialYdz.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dialYdz.setMaximum(200)
        self.dialYdz.setSingleStep(5)
        self.dialYdz.setPageStep(50)
        self.dialYdz.setNotchTarget(4.0)
        self.dialYdz.setNotchesVisible(True)
        self.dialYdz.setObjectName("dialYdz")
        self.oYdz = QtWidgets.QLabel(self.grpStick)
        self.oYdz.setGeometry(QtCore.QRect(655, 135, 40, 20))
        self.oYdz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oYdz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.oYdz.setAlignment(QtCore.Qt.AlignCenter)
        self.oYdz.setObjectName("oYdz")
        self.lYdz = QtWidgets.QLabel(self.grpStick)
        self.lYdz.setGeometry(QtCore.QRect(655, 115, 40, 20))
        self.lYdz.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lYdz.setAlignment(QtCore.Qt.AlignCenter)
        self.lYdz.setObjectName("lYdz")
        self.oXdz = QtWidgets.QLabel(self.grpStick)
        self.oXdz.setGeometry(QtCore.QRect(25, 135, 40, 20))
        self.oXdz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oXdz.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.oXdz.setAlignment(QtCore.Qt.AlignCenter)
        self.oXdz.setObjectName("oXdz")
        self.lXdz = QtWidgets.QLabel(self.grpStick)
        self.lXdz.setGeometry(QtCore.QRect(25, 115, 40, 20))
        self.lXdz.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lXdz.setAlignment(QtCore.Qt.AlignCenter)
        self.lXdz.setObjectName("lXdz")
        self.dialXdz = QtWidgets.QDial(self.grpStick)
        self.dialXdz.setGeometry(QtCore.QRect(70, 110, 50, 50))
        self.dialXdz.setMaximum(200)
        self.dialXdz.setSingleStep(5)
        self.dialXdz.setPageStep(50)
        self.dialXdz.setNotchTarget(4.0)
        self.dialXdz.setNotchesVisible(True)
        self.dialXdz.setObjectName("dialXdz")
        self.lYAxisName = QtWidgets.QLabel(self.grpStick)
        self.lYAxisName.setGeometry(QtCore.QRect(-10, 25, 100, 35))
        self.lYAxisName.setAlignment(QtCore.Qt.AlignCenter)
        self.lYAxisName.setObjectName("lYAxisName")
        self.lXAxisName = QtWidgets.QLabel(self.grpStick)
        self.lXAxisName.setGeometry(QtCore.QRect(-10, 210, 100, 35))
        self.lXAxisName.setAlignment(QtCore.Qt.AlignCenter)
        self.lXAxisName.setObjectName("lXAxisName")
        self.grpThumbStick = QtWidgets.QFrame(self.grpStick)
        self.grpThumbStick.setGeometry(QtCore.QRect(365, 50, 155, 185))
        self.grpThumbStick.setObjectName("grpThumbStick")
        self.lThumbStickPush = QtWidgets.QLabel(self.grpThumbStick)
        self.lThumbStickPush.setGeometry(QtCore.QRect(50, 90, 55, 25))
        self.lThumbStickPush.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbStickPush.setObjectName("lThumbStickPush")
        self.kThumbStickW = QtWidgets.QPushButton(self.grpThumbStick)
        self.kThumbStickW.setGeometry(QtCore.QRect(20, 65, 35, 25))
        self.kThumbStickW.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbStickW.setText("")
        self.kThumbStickW.setObjectName("kThumbStickW")
        self.kThumbStickPush = QtWidgets.QPushButton(self.grpThumbStick)
        self.kThumbStickPush.setGeometry(QtCore.QRect(60, 65, 35, 25))
        self.kThumbStickPush.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbStickPush.setText("")
        self.kThumbStickPush.setObjectName("kThumbStickPush")
        self.lThumbStickE = QtWidgets.QLabel(self.grpThumbStick)
        self.lThumbStickE.setGeometry(QtCore.QRect(90, 90, 55, 25))
        self.lThumbStickE.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbStickE.setObjectName("lThumbStickE")
        self.kThumbStickS = QtWidgets.QPushButton(self.grpThumbStick)
        self.kThumbStickS.setGeometry(QtCore.QRect(60, 115, 35, 25))
        self.kThumbStickS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbStickS.setText("")
        self.kThumbStickS.setObjectName("kThumbStickS")
        self.lThumbStickS = QtWidgets.QLabel(self.grpThumbStick)
        self.lThumbStickS.setGeometry(QtCore.QRect(50, 140, 55, 25))
        self.lThumbStickS.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbStickS.setObjectName("lThumbStickS")
        self.lThumbStickN = QtWidgets.QLabel(self.grpThumbStick)
        self.lThumbStickN.setGeometry(QtCore.QRect(50, 5, 55, 25))
        self.lThumbStickN.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbStickN.setObjectName("lThumbStickN")
        self.kThumbStickE = QtWidgets.QPushButton(self.grpThumbStick)
        self.kThumbStickE.setGeometry(QtCore.QRect(100, 65, 35, 25))
        self.kThumbStickE.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbStickE.setText("")
        self.kThumbStickE.setObjectName("kThumbStickE")
        self.lThumbStickW = QtWidgets.QLabel(self.grpThumbStick)
        self.lThumbStickW.setGeometry(QtCore.QRect(10, 90, 55, 25))
        self.lThumbStickW.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbStickW.setObjectName("lThumbStickW")
        self.kThumbStickN = QtWidgets.QPushButton(self.grpThumbStick)
        self.kThumbStickN.setGeometry(QtCore.QRect(60, 30, 35, 25))
        self.kThumbStickN.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbStickN.setText("")
        self.kThumbStickN.setObjectName("kThumbStickN")
        self.lThumbOutBAddon = QtWidgets.QLabel(self.grpStick)
        self.lThumbOutBAddon.setGeometry(QtCore.QRect(520, 135, 95, 25))
        self.lThumbOutBAddon.setAlignment(QtCore.Qt.AlignCenter)
        self.lThumbOutBAddon.setObjectName("lThumbOutBAddon")
        self.kThumbBAddon = QtWidgets.QPushButton(self.grpStick)
        self.kThumbBAddon.setGeometry(QtCore.QRect(550, 110, 35, 25))
        self.kThumbBAddon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kThumbBAddon.setText("")
        self.kThumbBAddon.setObjectName("kThumbBAddon")
        self.lGPADColor = QtWidgets.QLabel(self.centralwidget)
        self.lGPADColor.setGeometry(QtCore.QRect(60, 260, 45, 30))
        self.lGPADColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lGPADColor.setObjectName("lGPADColor")
        self.lKEYBColor = QtWidgets.QLabel(self.centralwidget)
        self.lKEYBColor.setGeometry(QtCore.QRect(10, 260, 45, 30))
        self.lKEYBColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lKEYBColor.setObjectName("lKEYBColor")
        self.lBOTHColor = QtWidgets.QLabel(self.centralwidget)
        self.lBOTHColor.setGeometry(QtCore.QRect(110, 260, 45, 30))
        self.lBOTHColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lBOTHColor.setObjectName("lBOTHColor")
        windowMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(windowMain)
        QtCore.QMetaObject.connectSlotsByName(windowMain)
        windowMain.setTabOrder(self.comList, self.bScanSerial)
        windowMain.setTabOrder(self.bScanSerial, self.bRetrieve)
        windowMain.setTabOrder(self.bRetrieve, self.bSendAll)
        windowMain.setTabOrder(self.bSendAll, self.bClearAll)
        windowMain.setTabOrder(self.bClearAll, self.chkPinkyAddon)
        windowMain.setTabOrder(self.chkPinkyAddon, self.kPinkyB1)
        windowMain.setTabOrder(self.kPinkyB1, self.kPinkyB2)
        windowMain.setTabOrder(self.kPinkyB2, self.kPinkyB3)
        windowMain.setTabOrder(self.kPinkyB3, self.kPinkyB4)
        windowMain.setTabOrder(self.kPinkyB4, self.kPinkyB5)
        windowMain.setTabOrder(self.kPinkyB5, self.kPinkyBAddon)
        windowMain.setTabOrder(self.kPinkyBAddon, self.kRingB1)
        windowMain.setTabOrder(self.kRingB1, self.kRingB2)
        windowMain.setTabOrder(self.kRingB2, self.kRingB3)
        windowMain.setTabOrder(self.kRingB3, self.kRingB4)
        windowMain.setTabOrder(self.kRingB4, self.kRingB5)
        windowMain.setTabOrder(self.kRingB5, self.kMiddleB1)
        windowMain.setTabOrder(self.kMiddleB1, self.kMiddleB2)
        windowMain.setTabOrder(self.kMiddleB2, self.kMiddleB3)
        windowMain.setTabOrder(self.kMiddleB3, self.kMiddleB4)
        windowMain.setTabOrder(self.kMiddleB4, self.kMiddleB5)
        windowMain.setTabOrder(self.kMiddleB5, self.chkIndexAddon)
        windowMain.setTabOrder(self.chkIndexAddon, self.kIndexB1)
        windowMain.setTabOrder(self.kIndexB1, self.kIndexB2)
        windowMain.setTabOrder(self.kIndexB2, self.kIndexB3)
        windowMain.setTabOrder(self.kIndexB3, self.kIndexB4)
        windowMain.setTabOrder(self.kIndexB4, self.kIndexB5)
        windowMain.setTabOrder(self.kIndexB5, self.kIndexBAddon)
        windowMain.setTabOrder(self.kIndexBAddon, self.kThumbNavN)
        windowMain.setTabOrder(self.kThumbNavN, self.kThumbNavE)
        windowMain.setTabOrder(self.kThumbNavE, self.kThumbNavS)
        windowMain.setTabOrder(self.kThumbNavS, self.kThumbNavW)
        windowMain.setTabOrder(self.kThumbNavW, self.kThumbNavPush)
        windowMain.setTabOrder(self.kThumbNavPush, self.kThumbStickN)
        windowMain.setTabOrder(self.kThumbStickN, self.kThumbStickE)
        windowMain.setTabOrder(self.kThumbStickE, self.kThumbStickS)
        windowMain.setTabOrder(self.kThumbStickS, self.kThumbStickW)
        windowMain.setTabOrder(self.kThumbStickW, self.kThumbStickPush)

    def retranslateUi(self, windowMain):
        _translate = QtCore.QCoreApplication.translate
        windowMain.setWindowTitle(_translate("windowMain", "gameKey Configuration"))
        self.grpMiddle.setTitle(_translate("windowMain", "Middle"))
        self.lMiddleB3.setText(_translate("windowMain", "B3"))
        self.lMiddleB2.setText(_translate("windowMain", "B2"))
        self.lMiddleB4.setText(_translate("windowMain", "B4"))
        self.lMiddleB1.setText(_translate("windowMain", "B1"))
        self.lMiddleB5.setText(_translate("windowMain", "B5"))
        self.grpPinky.setTitle(_translate("windowMain", "Pinky"))
        self.lPinkyB1.setText(_translate("windowMain", "B1"))
        self.lPinkyB2.setText(_translate("windowMain", "B2"))
        self.lPinkyB3.setText(_translate("windowMain", "B3"))
        self.lPinkyB4.setText(_translate("windowMain", "B4"))
        self.lPinkyB5.setText(_translate("windowMain", "B5"))
        self.lPinkyBAddon.setText(_translate("windowMain", "Side"))
        self.chkPinkyAddon.setText(_translate("windowMain", "Addon"))
        self.grpRing.setTitle(_translate("windowMain", "Ring"))
        self.lRingB3.setText(_translate("windowMain", "B3"))
        self.lRingB2.setText(_translate("windowMain", "B2"))
        self.lRingB4.setText(_translate("windowMain", "B4"))
        self.lRingB1.setText(_translate("windowMain", "B1"))
        self.lRingB5.setText(_translate("windowMain", "B5"))
        self.bSendAll.setText(_translate("windowMain", "Send Config"))
        self.grpIndex.setTitle(_translate("windowMain", "Index"))
        self.chkIndexAddon.setText(_translate("windowMain", "Addon"))
        self.lIndexBAddon.setText(_translate("windowMain", "Side"))
        self.lIndexB3.setText(_translate("windowMain", "B3"))
        self.lIndexB2.setText(_translate("windowMain", "B2"))
        self.lIndexB4.setText(_translate("windowMain", "B4"))
        self.lIndexB1.setText(_translate("windowMain", "B1"))
        self.lIndexB5.setText(_translate("windowMain", "B5"))
        self.bClearAll.setText(_translate("windowMain", "Clear All"))
        self.grpThumbNav.setTitle(_translate("windowMain", "Thumb 5-Way"))
        self.lThumbNavN.setText(_translate("windowMain", "Up"))
        self.lThumbNavS.setText(_translate("windowMain", "Down"))
        self.lThumbNavE.setText(_translate("windowMain", "Fwd"))
        self.lThumbNavW.setText(_translate("windowMain", "Back"))
        self.lThumbNavPush.setText(_translate("windowMain", "Push"))
        self.bScanSerial.setText(_translate("windowMain", "Scan for gameKeys"))
        self.bRetrieve.setText(_translate("windowMain", "Retrieve Config"))
        self.grpConfig.setTitle(_translate("windowMain", "Config File"))
        self.bConfigSave.setText(_translate("windowMain", "Save"))
        self.bConfigSaveAs.setText(_translate("windowMain", "SaveAs"))
        self.bConfigRefresh.setText(_translate("windowMain", "Refresh List"))
        self.bConfigLoad.setText(_translate("windowMain", "Reload"))
        self.lDevN.setText(_translate("windowMain", "Dev Name:"))
        self.lDevF.setText(_translate("windowMain", "FW Ver:"))
        self.bSaveEEPROM.setText(_translate("windowMain", "Save Onboard Memory"))
        self.grpStick.setTitle(_translate("windowMain", "Analog Stick"))
        self.lXCur.setText(_translate("windowMain", "X Current"))
        self.lYCur.setText(_translate("windowMain", "Y Current"))
        self.iXInvert.setText(_translate("windowMain", "X Invert"))
        self.iYInvert.setText(_translate("windowMain", "Y Invert"))
        self.bResetAxes.setText(_translate("windowMain", "Reset Stick"))
        self.bSendAxes.setText(_translate("windowMain", "Send Stick"))
        self.bUpdateAnalog.setText(_translate("windowMain", "Update Current"))
        self.oYdz.setText(_translate("windowMain", "dzv"))
        self.lYdz.setText(_translate("windowMain", "Y DZ"))
        self.oXdz.setText(_translate("windowMain", "dzv"))
        self.lXdz.setText(_translate("windowMain", "X DZ"))
        self.lYAxisName.setText(_translate("windowMain", "Y Axis\n"
"Fwd/Back"))
        self.lXAxisName.setText(_translate("windowMain", "X Axis\n"
"Up/Down"))
        self.lThumbStickPush.setText(_translate("windowMain", "Push"))
        self.lThumbStickE.setText(_translate("windowMain", "Fwd"))
        self.lThumbStickS.setText(_translate("windowMain", "Down"))
        self.lThumbStickN.setText(_translate("windowMain", "Up"))
        self.lThumbStickW.setText(_translate("windowMain", "Back"))
        self.lThumbOutBAddon.setText(_translate("windowMain", "Outer Thumb"))
        self.lGPADColor.setText(_translate("windowMain", "GPAD"))
        self.lKEYBColor.setText(_translate("windowMain", "KEYB"))
        self.lBOTHColor.setText(_translate("windowMain", "BOTH"))
from superqt import QLabeledRangeSlider


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowMain = QtWidgets.QMainWindow()
    ui = Ui_windowMain()
    ui.setupUi(windowMain)
    windowMain.show()
    sys.exit(app.exec_())
