# Based on docker-pyinstaller by cdrx
# https://github.com/cdrx/docker-pyinstaller

FROM python:3.10.13-bullseye
SHELL ["/bin/bash", "-i", "-c"]

ARG PYINSTALLER_VERSION=5.13.2

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-linux.sh /entrypoint.sh

RUN pip3 install pyinstaller==$PYINSTALLER_VERSION \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
